language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  local-dir: examples
keep-history: true