language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
  - yarn run test
before_deploy:
  - yarn run docs
  - mkdir ghpages
  - mv ./docs ./ghpages/docs
  - mv ./examples/index.html ./ghpages/index.html
  - mv ./examples/examples.bundle.js ./ghpages/examples.bundle.js
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  local-dir: ghpages
keep-history: true

jobs:
  include:
    - stage: Get Test Coverage
      node_js: node
      script: yarn run test:coveralls