language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run build
  - yarn run test
  - yarn run docs
  - mv ./docs ./examples/docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  local-dir: examples
keep-history: true

jobs:
  include:
    - stage: Get Test Coverage
      node_js: node
      script: yarn run test:coveralls